export enum validationMsg {
  firstNameRequiredMsg = "الاسم الاول مطلوب",
  firstNameMinLimitMsg = "الاسم الاول قصير",
  firstNameMaxLimitMsg = " الاسم الاول طويل",
  lastNameRequiredMsg = "الاسم الثاني مطلوب",
  lastNameMinLimitMsg = "الاسم الثاني قصير",
  lastNameMaxLimitMsg = "الاسم الثاني طويل",
  emailRequiredMsg = "البريد الالكتروني مطلوب",
  emailValidMsg = "نعتذر, هذا ليس بريد الالكتروني",
  passwordRequiredMsg = "السر مطلوب",
  passwordMinLimitMsg = "كلمة السر اقصر من 6 احرف",
  passwordMaxLimitMsg = "كلمة السر اطول من 16 حرف",
  confirmPasswordRequiredMsg = "تاكيد السر مطلوب",
  confirmPasswordMatchingMsg = "السر غير مطابق",
  birthdayValidMsg = "يوم الميلاد مطلوب",
  genderValidMsg = "الجنس مطلوب",
  arabicOnly = "العربية فقط",
  noNumbers = "يجب ان لا يحتوي الاسم على ارقام",
  englishValid = "العربية فقط",
  fieldRequired = "الحقل مطلوب",
}
